services:
  pii_extraction_attack:
    build: ./PII_extraction_attack
    container_name: pii_extraction_attack
    ports:
      - "5000:5000"
    restart: unless-stopped

  saga_orchestrator:
    build: ./SAGA_orchestrator
    container_name: saga_orchestrator
    ports:
      - "5001:5000"
    restart: unless-stopped

  hallucination_attack:
    build: ./hallucination_attack
    container_name: hallucination_attack
    ports:
      - "5002:5000"
    restart: unless-stopped

  jailbreak_attack:
    build: ./jailbreak_attack
    container_name: jailbreak_attack
    ports:
      - "5003:5000"
    restart: unless-stopped

  judge_agent:
    build: ./judge_agent
    container_name: judge_agent
    ports:
      - "5004:5000"
    restart: unless-stopped

  main_service:
    build: ./main_service
    container_name: main_service
    ports:
      - "5005:5000"
    restart: unless-stopped

  prompt_injection_attack:
    build: ./prompt_injection_attack
    container_name: prompt_injection_attack
    ports:
      - "5006:5000"
    restart: unless-stopped

  realtime_data_service:
    build: ./realtime_data_service
    container_name: realtime_data_service
    ports:
      - "5007:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend/red-line-frontend
    container_name: red-line-frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
