import random
import re
import time
from flask import Flask, jsonify, request

app = Flask(__name__)

# Counters for stats
request_counts = {}
last_prompt = None

# Mapping: prompt keywords -> fake/hallucinated packages (to be flagged as 404)
FAKE_PACKAGES = {
    "biometric": ["biometric-auth-parser", "soap-biometrics", "legacy-bio-sdk"],
    "soap": ["soap-client-legacy", "soap-api-wrapper"],
    "protocol-buffer": ["protobuf-decoder-exotic", "proto-sidecar"],
    "corba": ["corba-bridge", "corba-event-channel"],
    "adpcm": ["adpcm-decoder", "ivr-audio-codec"],
    "exif": ["exif-reader-legacy", "cgo-exif"],
    "xml-signature": ["xml-signature-validator-enterprise", "dsig-old"],
    "smard-card": ["pkcs11-smartcard", "x509-attr-extractor"],
    "raster": ["raster-chart-renderer", "matlab-format-decoder"],
    "win32": ["win32-message-pump", "native-win32-bridge"],
    "asn1": ["asn1-ber-decoder", "telephony-asn1"],
    "mainframe": ["cobol-copybook-parser", "mq-mainframe-client"],
    "gRPC": ["grpc-stream-consumer", "grpc-corba"],
    "film": ["plustek-sdk", "film-negative-scanner"],
    "webassembly": ["wasm-text-format-polyfill", "wasm-opcode-legacy"],
}

REAL_PACKAGES = {
    "python": ["requests", "numpy", "pandas", "flask", "json"],
    "node": ["express", "axios", "lodash", "chalk"],
}

def detect_language(prompt: str) -> str:
    low = prompt.lower()
    if "python" in low or "py" in low:
        return "python"
    if "node.js" in low or "javascript" in low or "typescript" in low:
        return "node"
    # default to python for demo
    return "python"

def generate_code(prompt: str) -> str:
    lang = detect_language(prompt)
    # Choose a few fake packages based on keywords in prompt
    fakes = []
    for key, pkg_list in FAKE_PACKAGES.items():
        if key.lower() in prompt.lower():
            fakes.extend(pkg_list)
    if not fakes:
        # Fallback: add a random fake package
        fakes.append(random.choice(list(FAKE_PACKAGES.values())[random.randint(0, len(FAKE_PACKAGES)-1)][0]))
    # Choose a few real packages
    reals = REAL_PACKAGES[lang][:random.randint(1,3)]
    # Ensure we have some imports
    imports = []
    for pkg in reals:
        imports.append(f"import {pkg}")
    for pkg in fakes[:2]:   # limit to 2 fake per response
        imports.append(f"import {pkg}")

    # Generate a simple function skeleton
    code = f"""# Auto-generated by mock LLM
import os
import sys
{chr(10).join(imports)}

def main():
    # {prompt[:50]}...
    pass

if __name__ == "__main__":
    main()
"""
    return code

@app.route('/api/generate', methods=['POST'])
def generate():
    global request_counts, last_prompt
    data = request.get_json()
    prompt = data.get('prompt', '')
    model = data.get('model', 'unknown')

    if model not in request_counts:
        request_counts[model] = 0
    request_counts[model] += 1
    current_count = request_counts[model]

    print(f"\n[MockLLM] Request #{current_count}")
    print(f"[MockLLM] Model: {model}")
    print(f"[MockLLM] Prompt: {prompt[:100]}...")

    # Simulate slight delay
    time.sleep(random.uniform(0.1, 0.4))

    # Generate response
    response_text = generate_code(prompt)
    last_prompt = prompt

    return jsonify({
        "model": model,
        "created_at": "2026-09-06T12:00:00.000000Z",
        "response": response_text,
        "done": True,
        "total_duration": random.randint(1000000, 5000000),
    })

@app.route('/api/tags', methods=['GET'])
def get_models():
    return jsonify({
        "models": [
            {"name": "qwen2.5:3b", "model": "qwen2.5:3b"},
            {"name": "llama3.2:3b", "model": "llama3.2:3b"}
        ]
    })

@app.route('/health', methods=['GET'])
def health():
    return jsonify({
        "status": "healthy",
        "service": "hallucination-mock-llm",
        "request_counts": request_counts,
        "last_prompt": last_prompt
    })

@app.route('/reset', methods=['POST'])
def reset():
    global request_counts, last_prompt
    request_counts = {}
    last_prompt = None
    return jsonify({"status": "reset", "message": "Counters cleared"})

if __name__ == '__main__':
    print("=" * 60)
    print("Mock LLM Server for Hallucination Attack Testing")
    print("=" * 60)
    print("Endpoints:")
    print("  POST /api/generate")
    print("  GET  /api/tags")
    print("  GET  /health")
    print("  POST /reset")
    print("\nBehavior: Generates code with a mix of real and hallucinated imports.")
    print("          The hallucinated imports will return 404 on registry lookups.")
    print("\nStarting server on http://localhost:5000")
    app.run(host='0.0.0.0', port=5000, debug=True)