# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: log.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'log.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlog.proto\x12\x06\x65vents\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x02\n\x03Log\x12\x18\n\x10job_service_name\x18\x01 \x01(\t\x12\x10\n\x08nodeName\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x11\n\tnodeInput\x18\x04 \x01(\t\x12\x12\n\nnodeOutput\x18\x05 \x01(\t\x12\x11\n\ttargetUrl\x18\x06 \x01(\t\x12/\n\x0btimeRunning\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10\x62udget_remaining\x18\x08 \x01(\t\x12\x19\n\x11\x61\x64\x64itionalMessage\x18\t \x01(\t\x12\x12\n\njobRequest\x18\n \x01(\t\x12\x14\n\x0cjob_response\x18\x0b \x01(\t\x12,\n$executionLogSectionForTheTransaction\x18\x0c \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOG']._serialized_start=55
  _globals['_LOG']._serialized_end=369
# @@protoc_insertion_point(module_scope)
